### ISSUE TITLE
Dependency Injection for Controller

### ISSUE THREAD

**Issue by fastsol** [jenssegers/lean#4]
Does this package allow for DI in the controller?  I'm trying to integrate it into an already existing slim project but when I try to type-hint a class in the controller method being called, it's not allowing it to be autowired in.

Am I doing something wrong or does this package not work for that aspect of Slim3

**Comment by mstaack** [comment]
i would expect it to only work inside the controllers construct method..

**Comment by jenssegers** [comment]
Yeah currently only the constructor arguments are auto-injected by the container. I think Laravel is the only framework that does this, but I don't agree that that would be best practice.

I could try and find a way to optionally enable method injection if you want.

**Comment by mstaack** [comment]
@jenssegers at first i want to thank you for all your open source code.. :) cool stuff!

whats your point regarding injection into controller actions? testing abilities?

you would probably need to hook into fast-route's handler resolving logic

**Comment by fastsol** [comment]
@jenssegers making it work like Laravel or as close as possible would be awesome.  Yes I realize that I could use Laravel instead but that framework is like having a mansion but you really only need a rambler for many projects.

**Comment by jenssegers** [comment]
It seems that method reflection became a bit difficult since the latest version of the League's container. I opened an issue here: https://github.com/thephpleague/container/issues/161

**Comment by mstaack** [comment]
@jenssegers whats your plan now?

**Comment by jenssegers** [comment]
@mstaack It took me a while, but I'm preparing a new release that will have back method injection.

Can you check out the current dev-master? Will close this issue for now :)

**Comment by mstaack** [comment]
@jenssegers just beautiful! thank you very much
