### ISSUE TITLE
Possible to set errorHandler, etc?

### ISSUE THREAD

**Issue by alturic** [jenssegers/lean#5]
I admit I’m new to OOP, but I’ve setup Slim to override its internal errorHandler to use Monolog using Pimple before. I cannot for the life of me figure out how to do it using this package though?

**Comment by jenssegers** [comment]
I'll take a look and add it to the readme!

**Comment by jenssegers** [comment]
@alturic I'm preparing a new major version and updated the readme. Can you check out dev-master and see if you can get it working now?

Will close this issue for now :)
